//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gästebuch.Models
    {
    /// <summary>
    /// Defines the <see cref="tbl_ChangeLog" />.
    /// </summary>
    public partial class tbl_ChangeLog
        {
        /// <summary>
        /// Gets or sets the LogId.
        /// </summary>
        public int LogId { get; set; }

        /// <summary>
        /// Gets or sets the Databasename.
        /// </summary>
        public string Databasename { get; set; }

        /// <summary>
        /// Gets or sets the EventType.
        /// </summary>
        public string EventType { get; set; }

        /// <summary>
        /// Gets or sets the ObjectName.
        /// </summary>
        public string ObjectName { get; set; }

        /// <summary>
        /// Gets or sets the ObjectType.
        /// </summary>
        public string ObjectType { get; set; }

        /// <summary>
        /// Gets or sets the SqlCommand.
        /// </summary>
        public string SqlCommand { get; set; }

        /// <summary>
        /// Gets or sets the EventDate.
        /// </summary>
        public System.DateTime EventDate { get; set; }

        /// <summary>
        /// Gets or sets the LoginName.
        /// </summary>
        public string LoginName { get; set; }
        }
    }
