//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gästebuch.Models
    {
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Defines the <see cref="tbl_Admin" />.
    /// </summary>
    public partial class tbl_Admin
        {
        /// <summary>
        /// Gets or sets the rowguid.
        /// </summary>
        public System.Guid rowguid { get; set; }

        /// <summary>
        /// Gets or sets the Username.
        /// </summary>
        [DisplayName("Username*")]
        [Required(ErrorMessage = "This Field is Required")]
        public string Username { get; set; }

        /// <summary>
        /// Gets or sets the Passwort.
        /// </summary>
        [DisplayName("Password*")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This Field is Required")]
        public string Passwort { get; set; }

        /// <summary>
        /// Gets or sets the LoginErrorMsg.
        /// </summary>
        public string LoginErrorMsg { get; set; }
        }
    }
