//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gästebuch.Models
    {
    using System;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Defines the <see cref="tbl_Einträge" />.
    /// </summary>
    public partial class tbl_Einträge
        {
        /// <summary>
        /// Gets or sets the rowguid.
        /// </summary>
        public System.Guid rowguid { get; set; }

        /// <summary>
        /// Gets or sets the Nachname.
        /// </summary>
        [Required(ErrorMessage = "This Field is Required")]
        public string Nachname { get; set; }

        /// <summary>
        /// Gets or sets the Vorname.
        /// </summary>
        [Required(ErrorMessage = "This Field is Required")]
        public string Vorname { get; set; }

        /// <summary>
        /// Gets or sets the Bewertung.
        /// </summary>
        [Required(ErrorMessage = "This Field is Required")]
        public string Bewertung { get; set; }

        /// <summary>
        /// Gets or sets the Verbesserungsvorschläge.
        /// </summary>
        [Required(ErrorMessage = "This Field is Required")]
        public string Verbesserungsvorschläge { get; set; }

        /// <summary>
        /// Gets or sets the Zeitpunkt.
        /// </summary>
        [Required(ErrorMessage = "This Field is Required")]
        public DateTime Zeitpunkt { get; set; }

        /// <summary>
        /// Gets or sets the Autorisiert.
        /// </summary>
        public Boolean Autorisiert { get; set; }
        }
    }
